games_roles = {
    "🚔": "A Way Out",
    "👽": "Among Us",
    "🏝️": "Animal Crossing: New Horizons",
    "🏆": "Apex Legends",
    "🦖": "ARK: Survival Evolved",
    "💥": "Borderlands 3",
    "🪖": "Call of Duty: Warzone",
    "🔫": "Counter Strike 2",
    "🤖": "Cyberpunk 2077",
    "☠️": "DayZ",
    "🔪": "Dead by Daylight",
    "⛏️": "Deep Rock Galactic",
    "🌌": "Destiny 2",
    "🔮": "Dota 2",
    "💍": "Elden Ring",
    "🤸": "Fall Guys: Ultimate Knockout",
    "⚔️": "For Honor",
    "🏙️": "Fortnite",
    "🗺️": "Genshin Impact",
    "🚗": "GTA 5",
    "🔱": "Hades",
    "🦗": "Hollow Knight",
    "🔥": "League of Legends",
    "🧟": "Left 4 Dead 2",
    "🟩": "Minecraft",
    "🗡️": "Monster Hunter Rise",
    "🐉": "Monster Hunter: World",
    "🚀": "Overwatch 2",
    "🧙": "Path of Exile",
    "💰": "Payday 2",
    "👻": "Phasmophobia",
    "🏹": "PlayerUnknown's Battlegrounds",
    "🛡️": "Rainbow Six Siege",
    "🤠": "Red Dead Redemption 2",
    "🌧️": "Risk of Rain 2",
    "⚽": "Rocket League",
    "🔧": "Rust",
    "🏴‍☠️": "Sea of Thieves",
    "⚡": "Smite",
    "🌾": "Stardew Valley",
    "🌟": "Teamfight Tactics",
    "🔨": "Terraria",
    "🌿": "The Legend of Zelda: Breath of the Wild",
    "🐺": "The Witcher 3: Wild Hunt",
    "🤪": "Totally Accurate Battlegrounds",
    "🎯": "Valorant",
    "🕹️": "Warframe",
}