import disnake
from disnake.ext import commands
import os
from datetime import datetime
import pytz

MODERATION_CHANNEL_ID = 1252902441436057640
BANNED_WORDS = ['assfuck',
    'cuntfucker',
    'niggers',
    'niggerhole',
    'nigger',
    'balllicker',
    'nlgger',
    'porchmonkey',
    'Porch-monkey',
    'cunt',
    'asswhore',
    'fuck',
    'assjockey',
    'Dothead',
    'blacks',
    'cumqueen',
    'fatfucker',
    'Jigaboo',
    'jiggabo',
    'nlggor',
    'snownigger',
    'Spearchucker',
    'Timber-nigger',
    'shitnigger',
    'asslick',
    'shithead',
    'asshole',
    'asshole',
    'cuntlicker',
    'kunt',
    'spaghettinigger',
    'Towel-head',
    'Chernozhopy',
    'asslicker',
    'Bluegum',
    'twat',
    'ABCD',
    'bitchslap',
    'bulldyke',
    'choad',
    'cumshot',
    'fatass',
    'jigger',
    'kyke',
    'cumskin',
    'asian',
    'asscowboy',
    'assmuncher',
    'banging',
    'Burrhead',
    'Camel-Jockey',
    'coon',
    'crotchrot',
    'cumfest',
    'dicklicker',
    'fag',
    'fagot',
    'felatio',
    'fatfuck',
    'goldenshower',
    'hore',
    'jackoff',
    'jigg',
    'jigga',
    'jizjuice',
    'jizm',
    'jiz',
    'jigger',
    'jizzim',
    'kumming',
    'kunilingus',
    'Moolinyan',
    'motherfucking',
    'motherfuckings',
    'phuk',
    'Sheboon',
    'shitforbrains',
    'slanteye',
    'spick',
    'fuuck',
    'antinigger',
    'aperest',
    'Americoon',
    'ABC',
    'Aunt-Jemima',
    'queer',
    'anal',
    'asspirate',
    'addict',
    'bitch',
    'ass',
    'Buddhahead',
    'chode',
    'phuking',
    'phukking',
    'bastard',
    'bulldike',
    'dripdick',
    'assassination',
    'A-rab',
    'Buckra',
    'bootycall',
    'assholes',
    'assbagger',
    'cheesedick',
    'cooter',
    'cum',
    'cumquat',
    'cunnilingus',
    'datnigga',
    'deepthroat',
    'dick',
    'dickforbrains',
    'dickbrain',
    'dickless',
    'dike',
    'diddle',
    'dixiedyke',
    'Eskimo',
    'fannyfucker',
    'fatso',
    'fckcum',
    'Golliwog',
    'Goyim',
    'homobangers',
    'hooters',
    'Indognesial',
    'Indonesial',
    'jew',
    'jijjiboo',
    'knockers',
    'kummer',
    'mothafucka',
    'mooncricket',
    'Moon-Cricket',
    'Oven-Dodger',
    'Peckerwood',
    'phuked',
    'piccaninny',
    'picaninny',
    'phuq',
    'Polock',
    'poorwhitetrash',
    'prick',
    'pu55y',
    'Pshek',
    'slut',
    'jizzum',
    'cunteyed',
    'Spic',
    'Swamp-Guinea',
    'stupidfucker',
    'stupidfuck',
    'titfuck',
    'Twinkie',
    'cock',
    'Abeed',
    'analannie',
    'asshore',
    'Beaner',
    'Bootlip',
    'Burr-head',
    'buttfucker',
    'butt-fucker',
    'Uncle-Tom',
    'cocksmoker',
    'Africoon',
    'AmeriKKKunt',
    'antifaggot',
    'assklown',
    'asspuppies',
    'blackman',
    'jism',
    'blumpkin',
    'retard',
    'Gringo',
    'douchebag',
    'Piefke',
    'areola',
    'backdoorman',
    'Abbie',
    'bigbutt',
    'buttface',
    'cumbubble',
    'cumming',
    'Dego',
    'dong',
    'doggystyle',
    'doggiestyle',
    'erection',
    'feces',
    'goddamned',
    'gonzagas',
    'Greaser',
    'Greaseball',
    'handjob',
    'Half-breed',
    'horney',
    'jihad',
    'kumquat',
    'Lebo',
    'Moskal',
    'Mountain-Turk',
    'nofuckingway',
    'orgies',
    'orgy',
    'pecker',
    'poontang',
    'poon',
    'Polentone',
    'pu55i',
    'shitfuck',
    'shiteater',
    'shitdick',
    'sluts',
    'slutt',
    'Mangal',
    'Hymie',
    'stiffy',
    'titfucker',
    'twink',
    'asspacker',
    'barelylegal',
    'beaner',
    'Bozgor',
    'bumfuck',
    'shit for brains',
    'butchdyke',
    'butt-fuckers',
    'buttpirate',
    'cameljockey',
    'Carcamano',
    'Chankoro',
    'Choc-ice',
    'Chug',
    'Ciapaty-or-ciapak',
    'Cina',
    'cocksucer',
    'crackwhore',
    'Bougnoule',
    'unfuckable',
    'Africoon-Americoon',
    'Africoonia',
    'Americunt',
    'apesault',
    'Assburgers',
    'fucktardedness',
    'sheepfucker',
    'Wuhan-virus',
    'Wetback',
    'Aseng',
    'bumblefuck',
    'fastfuck',
    'itch',
    'nizzle',
    'Oriental',
    'cisgender',
    'ballsack',
    'penis',
    'zigabo',
    'Bule',
    'breastman',
    'bountybar',
    'Bounty-bar',
    'bondage',
    'bombing',
    'bullshit',
    'asses',
    'cancer',
    'cunilingus',
    'cummer',
    'dicklick',
    'ejaculation',
    'faeces',
    'fairy',
    'hoes',
    'idiot',
    'Laowai',
    'Leb',
    'muff',
    'muffdive',
    'Oreo',
    'orgasm',
    'orgasim',
    'osama',
    'peepshow',
    'Petrol-sniffer',
    'perv',
    'prickhead',
    'shitfit',
    'spermbag',
    'suckmytit',
    'suckmydick',
    'suckmyass',
    'suckme',
    'suckdick',
    'Yuon',
    'motherfucker',
    'groe',
    'Ali Baba',
    'retarded',
    'assfucker',
    'assmunch',
    'assranger',
    'Ayrab',
    'assclown',
    'buttfuck',
    'butt-fuck',
    'buttman',
    'Chink',
    'cocksucker',
    'cooly',
    'Coon-ass',
    'crotchmonkey',
    'Bohunk',
    'cockcowboy',
    'cocksmith',
    'catfucker',
    'fucktardedly',
    'trans-testicle',
    'Wigger',
    'whiskeydick',
    'aboriginal',
    'asskisser',
    'whitelist',
    'Latinx',
    'yambag',
    'boob',
    'beef curtains',
    'clunge',
    'af',
    'wokeness',
    'bitchez',
    'Iceberg Fuckers',
    'Zhyd',
    'bellend',
    'arsehole',
    'tatas',
    'assassinate',
    'boonga',
    'booby',
    'bullcrap',
    'defecate',
    'Dhoti',
    'dope',
    'hobo',
    'bigass',
    'hussy',
    'illegal',
    'ky',
    'moneyshot',
    'molestor',
    'nooner',
    'nookie',
    'nookey',
    'Paleface',
    'pansy',
    'peehole',
    'phonesex',
    'period',
    'pornking',
    'pornflick',
    'porn',
    'pooper',
    'sexwhore',
    'shitface',
    'shit',
    'slav',
    'slimeball',
    'sniggers',
    'snowback',
    'spermherder',
    'spankthemonkey',
    'spitter',
    'strapon',
    'Tacohead',
    'suckoff',
    'titbitnipply',
    'Turco-Albanian',
    'tranny',
    'trannie',
    'zhidovka',
    'zhid',
    'Bakra',
    'Afro engineering',
    'Ah Chah',
    'alligatorbait',
    'arabs',
    'Arabush',
    'Ashke-Nazi',
    'assblaster',
    'assmonkey',
    'badfuck',
    'bazongas',
    'beatoff',
    'bazooms',
    'Balija',
    'bunghole',
    'butchdike',
    'buttfuckers',
    'Boche',
    'buttbang',
    'butt-bang',
    'buttmunch',
    'Charlie',
    'chav',
    'Chinaman',
    'coloured',
    'boong',
    'butchbabes',
    'clit',
    'cockknob',
    'cocksucking',
    'cocktease',
    'Cokin',
    'anchor-baby',
    'cumsock',
    'fisting',
    'fuck-you',
    'Fritzie',
    'transgendered',
    'White-trash',
    'whitetrash',
    'whop',
    'wtf',
    'Vatnik',
    'welfare queen',
    'assman',
    'black',
    'Gyopo',
    'goddam',
    'minge',
    'punani',
    'douche',
    'doofus',
    'munter',
    'moron',
    'ballgag',
    'femsplaining',
    'asslover',
    'looney',
    'Boonga',
    'fat',
    'homosexual',
    'turd',
    'zhydovka',
    'effing',
    'minger',
    'dullard',
    'buggery',
    'brea5t',
    'boong',
    'addicted',
    'demon',
    'devilworshipper',
    'deth',
    'destroy',
    'doo-doo',
    'doodoo',
    'escort',
    'farting',
    'fairies',
    'husky',
    'incest',
    'Hunky',
    'jiggy',
    'laid',
    'molester',
    'Mzungu',
    'nigglings',
    'niggling',
    'niggles',
    'pee-pee',
    'pi55',
    'phungky',
    'porno',
    'pooping',
    'prostitute',
    'pros',
    'sexslave',
    'sextogo',
    'shag',
    'shithappens',
    'shithapens',
    'shitfull',
    'shitcan',
    'shinola',
    'slavedriver',
    'sleezeball',
    'spermhearder',
    'swastika',
    'shits',
    'trots',
    'trisexual',
    'twobitwhore',
    'Munt',
    'gangsta',
    'Abo',
    'addicts',
    'Alligator bait',
    'analsex',
    'Redskin',
    'Gypsy',
    'Ang mo',
    'Ape',
    'arab',
    'Aravush',
    'Armo',
    'arse',
    'assclown',
    'asswipe',
    'Beaney',
    'beatyourmeat',
    'bigbastard',
    'bitches',
    'Bogtrotter',
    'bung',
    'beaver',
    'bestial',
    'bogan',
    'Cabbage-Eater',
    'carpetmuncher',
    'carruth',
    'cocklover',
    'cockrider',
    'cornhole',
    'bollock',
    'Bog-Irish',
    'chinamen',
    'clamdigger',
    'clamdiver',
    'dwarf',
    'cakewalk',
    'ftw',
    'fml',
    'handicapped',
    'cawk',
    'carpet-muncher',
    'fuzzy-headed',
    'full-blood',
    'fuckity-bye',
    'frogess',
    'Norte',
    'troid',
    'willy',
    'pud',
    'pubiclice',
    'whitewashing',
    'Brit',]

class ModerationCog(commands.Cog):
    def __init__(self, bot: commands.Bot):
        self.bot = bot
        self.moderation_channel_id = MODERATION_CHANNEL_ID
        self.banned_words = BANNED_WORDS

        log_dir = os.path.join(os.path.dirname(__file__), '..', '..', 'logs', 'moderation')
        if not os.path.exists(log_dir):
            os.makedirs(log_dir)
        self.deleted_log_file_path = os.path.join(log_dir, 'deleted_messages_log.txt')
        self.ignored_log_file_path = os.path.join(log_dir, 'ignored_messages_log.txt')

    @commands.Cog.listener()
    async def on_message(self, message: disnake.Message):
        if message.author == self.bot.user:
            return

        if any(word in message.content.lower() for word in self.banned_words):
            await self.handle_banned_message(message)

    async def handle_banned_message(self, message: disnake.Message):
        moderation_channel = self.bot.get_channel(self.moderation_channel_id)
        if moderation_channel:
            view = self.ModerationButtons(message, self.deleted_log_file_path, self.ignored_log_file_path)
            await moderation_channel.send(
                f'Message ID: {message.id}\nAuthor: {message.author.mention}\nContent: {message.content}\nDate: {view.formatted_date}\n[Jump to Message](https://discord.com/channels/{message.guild.id}/{message.channel.id}/{message.id})', 
                view=view
            )
        else:
            print(f'Error: Could not find moderation channel with ID {self.moderation_channel_id}')

    class ModerationButtons(disnake.ui.View):
        def __init__(self, message: disnake.Message, deleted_log_file_path: str, ignored_log_file_path: str):
            super().__init__(timeout=None)
            self.message = message
            self.deleted_log_file_path = deleted_log_file_path
            self.ignored_log_file_path = ignored_log_file_path

            cet = pytz.timezone('CET')
            self.cet_time = message.created_at.astimezone(cet)

            self.formatted_date = self.cet_time.strftime('%d %B %Y')

        @disnake.ui.button(label="Delete Message", style=disnake.ButtonStyle.danger)
        async def delete_button(self, button: disnake.ui.Button, interaction: disnake.Interaction):
            await self.log_deleted_message()
            await self.message.delete()
            await interaction.response.send_message(f'Message by {self.message.author.mention} has been deleted.', ephemeral=True)
            await interaction.message.delete()

        @disnake.ui.button(label="Ignore", style=disnake.ButtonStyle.secondary)
        async def ignore_button(self, button: disnake.ui.Button, interaction: disnake.Interaction):
            await interaction.response.send_message('Message ignored. Deleting moderation alert.', ephemeral=True)
            await interaction.message.delete()
            self.stop()

        async def log_deleted_message(self):
            log_entry = self.format_log_entry()
            with open(self.deleted_log_file_path, 'a', encoding='utf-8') as log_file:
                log_file.write(log_entry)


        def format_log_entry(self):
            entry = (
                f"Message ID: {self.message.id}\n"
                f"Author: {self.message.author.name}#{self.message.author.discriminator} ({self.message.author.id})\n"
                f"Content: {self.message.content}\n"
                f"Channel: {self.message.channel.name} ({self.message.channel.id})\n"
                f"Time: {self.cet_time.strftime('%H:%M:%S')} CET, {self.formatted_date}\n\n"
            )
            return entry

def setup(bot: commands.Bot):
    bot.add_cog(ModerationCog(bot))